name: 'Build'
on: push
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.1", "3.2", "3.3", "3.4", "3.4.5"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby_version }}
      - name: Install dependencies
        run: bundle install
      - name: Lint Ruby files
        run: bundle exec rubocop
      - name: Run RSpec tests
        run: bundle exec rspec