name: 'Test against supported Faraday minor versions'
on: push
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Normally, we only test the most recent patch version for any given minor version.
        # For v2.0.x, we test v2.0.0 and v2.0.1 because v2.0.0 has a special behaviour where
        # the Net::HTTP adapter is not included. See
        # https://github.com/lostisland/faraday/blob/main/UPGRADING.md#faraday-20.
        faraday_version: ['1.1.0', '1.2.0', '1.3.1', '1.4.3', '1.5.1', '1.6.0', '1.7.2', '1.8.0', '1.9.3', '1.10.3', '2.0.0', '2.0.1', '2.1.0', '2.2.0', '2.3.0', '2.4.0', '2.5.2', '2.6.0', '2.7.12', '2.8.1', '2.9.2', '2.10.1', '2.11.0']
    env:
      FARADAY_VERSION: ~> ${{ matrix.faraday_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - name: Install dependencies
        run: bundle install
      - name: Run RSpec tests
        run: bundle exec rspec
